blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/LihvoDruida/Max-Camera-Distance/discussions
    about: Please ask questions here before opening an issue.